InvestmentManager/InvestmentManager/Controllers/InvestmentAccountsController.cs
using InvestmentManager.Core.DataAccess;
using InvestmentManager.Core.Services;
using InvestmentManager.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace InvestmentManager.Controllers
{
    public class InvestmentAccountsController : Controller
    {
        public InvestmentAccountsController(ITradeDateRepository tradeDateRepository, 
            IInvestmentAccountRepository accountRepository, RateOfReturnService rateOfReturnService)
        {
            this.tradeDateRepository = tradeDateRepository;
            this.accountRepository = accountRepository;
            this.rateOfReturnService = rateOfReturnService;
        }

        private ITradeDateRepository tradeDateRepository;
        private IInvestmentAccountRepository accountRepository;
        private RateOfReturnService rateOfReturnService;

        // GET: InvestmentAccounts
        public ActionResult Index()
        {
            var currentTradeDate = tradeDateRepository.GetLatestTradeDate();

            var accounts = this.accountRepository.LoadInvestmentAccounts(currentTradeDate).ToList();

            return View(accounts);
        }

        // GET: InvestmentAccounts/Details/XYZ1234567
        [Route("[controller]/[action]/{accountNumber}")]
        public ActionResult Details(string accountNumber)
        {
            var currentTradeDate = tradeDateRepository.GetLatestTradeDate();

            var account = this.accountRepository.LoadInvestmentAccount(accountNumber, currentTradeDate);


            var performance = rateOfReturnService.CalculatePerformance(accountNumber);

            var viewModel = new InvestmentAccountDetailsModel()
            {
                TradeDate = currentTradeDate,
                InvestmentAccount = account,
                CurrentPerformance = performance.LastOrDefault()
            };

            return View(viewModel);
        }

        // GET: InvestmentAccounts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InvestmentAccounts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InvestmentAccounts/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InvestmentAccounts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InvestmentAccounts/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InvestmentAccounts/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

InvestmentManager/InvestmentManager/Controllers/MarketsController.cs
using Microsoft.AspNetCore.Mvc;

namespace InvestmentManager.Controllers
{
    public class MarketsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InvestmentManager/InvestmentManager/Controllers/SecuritiesController.cs
using InvestmentManager.Core.DataAccess;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace InvestmentManager.Controllers
{
    public class SecuritiesController : Controller
    {
        public SecuritiesController(ITradeDateRepository tradeDateRepository)
        {
            this.tradeDateRepository = tradeDateRepository;
        }

        public ITradeDateRepository tradeDateRepository;

        // GET: Securities
        public ActionResult Index()
        {
            var tradeDates = tradeDateRepository.LoadTradeDates()
                .OrderBy(d => d.Date);

            return View(tradeDates);
        }

        // GET: Securities/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

    }
}

InvestmentManager/InvestmentManager/Views/Shared/Components/StockIndex/StockIndexViewComponent.cs
using InvestmentManager.Core.DataAccess;
using InvestmentManager.Core.Domain;
using InvestmentManager.Core.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace InvestmentManager.Views.Shared.Components.StockIndex
{
    public class StockIndexViewComponent : ViewComponent
    {
        public StockIndexViewComponent(StockIndexService service, ITradeDateRepository tradeDateRepository)
        {
            this.stockIndexService = service;
            this.tradeDateRepository = tradeDateRepository;
        }

        private StockIndexService stockIndexService;
        private ITradeDateRepository tradeDateRepository;

        public async Task<IViewComponentResult> InvokeAsync(string indexCode)
        {
            var currentTradeDate = this.tradeDateRepository.GetLatestTradeDate();
            //Task<StockIndexInfo> indexTask = stockIndexService.GetStockIndexPrice(indexCode, currentTradeDate);
            //indexTask.Wait();

            //StockIndexInfo indexInfo = indexTask.Result;
            StockIndexInfo? indexInfo = await stockIndexService.GetStockIndexPrice(indexCode, currentTradeDate);

            return View("Default", indexInfo);
        }

    }
}

InvestmentManager/InvestmentManager/Views/Shared/_ErrorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Investment Manager</title>
    <base href='@Url.Content("~/")'>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Investment Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="InvestmentAccounts" asp-action="Index">Investment Accounts</a></li>
                    <li><a asp-area="" asp-controller="Securities" asp-action="Index">Securities</a></li>
                    <li><a asp-area="" asp-controller="Markets" asp-action="Index">Markets</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2018 - Investment Manager</p>
            <p class="text-center">
                This is a demonstration app only.  All people and accounts are completely fictional.<br />
                Nothing in this application is intended to be or should be interpreted as investment advice.
            </p>
            <p class="text-center">Stock price data provided for free by <a link="https://iextrading.com/developer/">IEX</a>. View IEX’s <a link="https://iextrading.com/api-exhibit-a/">Terms of Use</a>.</p>
        </footer>
    </div>
    <mini-profiler />
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

InvestmentManager/InvestmentManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Investment Manager</title>
    <base href='@Url.Content("~/")'>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Investment Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="InvestmentAccounts" asp-action="Index">Investment Accounts</a></li>
                    <li><a asp-area="" asp-controller="Securities" asp-action="Index">Securities</a></li>
                    <li><a asp-area="" asp-controller="Markets" asp-action="Index">Markets</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    
    <div style="background-color: lightgrey" class="body-content">
        <div class="container">
            <div class="row">
                <vc:stock-index index-code="DJIA"></vc:stock-index>
                <vc:stock-index index-code="NASDAQ"></vc:stock-index>
                <vc:stock-index index-code="SP500"></vc:stock-index>
                <vc:stock-index index-code="RUT"></vc:stock-index>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2018 - Investment Manager</p>
            <p class="text-center">
                The base code for this application was orginally from fellow Pluralsight Author <a href="https://app.pluralsight.com/profile/author/david-berry">David Berry</a>.<br />
                This is a demonstration app only.  All people and accounts are completely fictional.<br />
                Nothing in this application is intended to be or should be interpreted as investment advice.
            </p>
            <p class="text-center">Stock price data provided for free by <a link="https://iextrading.com/developer/">IEX</a>. View IEX’s <a link="https://iextrading.com/api-exhibit-a/">Terms of Use</a>.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>